# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190328_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='description default text', null=True),
        ),
    ]
